# Dockerfile
FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    g++ \
    nodejs \
    npm \
    git \
    curl \
    nano \
    vim

# Set the working directory
WORKDIR /home/tech-learn

# Default command (optional)
CMD ["bash"]
